PREFIX = 
SUFFIX =
ifeq ($(OS),Windows_NT)
    PREFIX = mingw32  
    SUFFIX = .exe
    LFLAGS := -LC:\MinGW\lib
    INCLUDE := -IC:\MinGW\include
else
    CFLAGS += `sdl2-config --cflags`
    PREFIX = x86_64-w64-mingw32
    LFLAGS := -Lexternal/SDL2/lib
endif

LFLAGS += -lm -mwindows -lmingw32 -lSDL2

OUT = hello.exe

CC := $(PREFIX)-gcc$(SUFFIX)
AR := $(PREFIX)-ar$(SUFFIX)
